### ISSUE TITLE
Need Java 11-compliant version of Wrapper._generate

### ISSUE THREAD

**Issue by russgold** [eclipse-ee4j/orb-gmbal-pfl#19]
As currently written the _generate methods of Wrapper use Unsafe.defineClass() to create the class in the specified class loader. That is not supported as of Java 11. Create an alternative Implementation that can use the new Bridge.defineClass(Class<?>, byte[]) method, passing in the current class on which the generate one is based.

**Comment by hs536** [comment]
GlassFish requires the module with these fixes to run on JDK 11, is there a plan to release it in the next few months?

**Comment by smillidge** [comment]
It's possible we can push a milestone with these PRs in if that helps?

**Comment by smillidge** [comment]
@hs536  @russgold  which is the latest branch of gmbal-pfl as there seems to be a 4.1.x branch and master is at 4.0.x? I was going to try and do a milestone release to staging but don't know which branch to release

**Comment by hs536** [comment]
The 4.1.0 branch seems to have the changes for JDK 11. These changes are included in the master, so in my opinion, the new release should be 4.1.1.

**Comment by smillidge** [comment]
OK I will raise a PR to merge 4.1.x branch into master

**Comment by smillidge** [comment]
@hs536 what milestone build do you need?

**Comment by hs536** [comment]
We need to release a new version (4.1.1) with the current code.

**Comment by smillidge** [comment]
When trying to do a staging build I get Jenkins error 

` + cp eclipse-jenkins/toolchains.xml /home/jenkins/.m2
  cp: cannot create regular file '/home/jenkins/.m2/toolchains.xml': Read-only file system
  Build step 'Execute shell' marked build as failure
`

Any idea? See https://ci.eclipse.org/orb/job/orb-gmbal-pfl-release-build/23/console

**Comment by hs536** [comment]
@smillidge There seems to be a conflict between the pipeline and the shell script.
I think the pipeline is right.

Pipeline:
```
    - mountPath: "/home/jenkins/.m2/toolchains.xml"
      name: "toolchains-xml"
      readOnly: true
      subPath: "toolchains.xml"
```
Shell:
```
#!/bin/bash -ex

# Install toolchains.xml
cp eclipse-jenkins/toolchains.xml ~/.m2
```

**Comment by hs536** [comment]
Could you check the configuration below and comment out the line in the shell script and try again?
https://ci.eclipse.org/orb/job/orb-gmbal-pfl-release-build/configure
```
#!/bin/bash -ex

# Install toolchains.xml
# cp eclipse-jenkins/toolchains.xml ~/.m2 ★★
```

**Comment by smillidge** [comment]
OK it's still failing I will have to come back to this after the M1 unless another orb committer can pick it up.
`[ERROR] Failed to execute goal org.apache.maven.plugins:maven-toolchains-plugin:1.1:toolchain (default) on project pfl: Cannot find matching toolchain definitions for the following toolchain types:
[ERROR] jdk [ version='1.8' ]
[ERROR] Please make sure you define the required toolchains in your ~/.m2/toolchains.xml file.
[ERROR] -> [Help 1]
[ERROR]`

**Comment by russgold** [comment]
I see that the toolchains installation is commented out. Does eclipse-jenkins/toolchains.xml even exist? The last time I released this jar, I had configured the build to copy the toolchains.xml from the project. It seems to have been modified.

**Comment by smillidge** [comment]
I just commented it out based off the original failure 

`+ cp eclipse-jenkins/toolchains.xml /home/jenkins/.m2 cp: cannot create regular file '/home/jenkins/.m2/toolchains.xml': Read-only file system Build step 'Execute shell' marked build as failure`

**Comment by smillidge** [comment]
Looks like the job may need a bit if a rewrite based on the new infra?

**Comment by russgold** [comment]
Sounds like it. Where is that documented?

**Comment by smillidge** [comment]
I know very little about Jenkins and maven but there is this wiki page. https://wiki.eclipse.org/JakartaEE_New_Infra_Release_Job

**Comment by russgold** [comment]
I've just sent an email to the CBI-dev list. I think the problem is in the Kubernetes pod definition, but I don't see how to edit it. Now I get to find out how active that list is.

**Comment by russgold** [comment]
And the answer is.. not very. I have receive one reply, noting that we don't need to define our own toolchains.xml. But the one built-in is not working. I've asked again and am hoping for some help.

**Comment by russgold** [comment]
We now have a successful DRY_RUN build https://ci.eclipse.org/orb/job/orb-gmbal-pfl-release-build/39/console - the key was skipping the tests. 

I presume that we should have those tests run, ideally in a range of jdks, elsewhere, such as travis, unless Eclipse provides that service as well.

But my attempt to stage the result < https://ci.eclipse.org/orb/job/orb-gmbal-pfl-release-build/40/console> ran into an authorization failure. So I'm asking again on the support list.

**Comment by smillidge** [comment]
The job is configured to use https://oss.sonatype.org/ however it should be https://jakarta.oss.sonatype.org I’ll see if I get time to fix it today although I have back to back meetings most of the day.

Steve

**Comment by smillidge** [comment]
The project needs an update to the parent pom to 1.0.6 see

``
<parent>
        <groupId>org.eclipse.ee4j</groupId>
        <artifactId>project</artifactId>
        <version>1.0.5</version>
    </parent>
``

**Comment by russgold** [comment]
Finally got a staging build to pass:

https://ci.eclipse.org/orb/job/orb-gmbal-pfl-release-build/44/console

With the new repo, we have all new profile IDs, so each build is going to need to be reconfigured appropriately.

**Comment by russgold** [comment]
Unfortunately, while it updates the POMs, it does so without signed commits, so presumably the branch cannot be merged.  I don't understand this process...

**Comment by smillidge** [comment]
@russgold if the unsigned commits are from an Eclipse Bot you can merge the changes as there is no IP implications.

**Comment by hs536** [comment]
Could the 4.1.1 release be registered in Maven Central?
https://mvnrepository.com/artifact/org.glassfish.pfl/pfl

**Comment by smillidge** [comment]
It is in staging so you can build GlassFish against it. I will look to see how to get it migrated over to central.

**Comment by russgold** [comment]
https://jenkins.eclipse.org/orb/job/orb-final-release is the job intended for that purpose.

**Comment by hs536** [comment]
> It is in staging so you can build GlassFish against it. I will look to see how to get it migrated over to central.

OK, I'll try it on Draft PR of GlassFish. Thanks!

**Comment by Cousjava** [comment]
4.1.1 and 4.1.2 still haven't appeared on Maven Central, although they are tagged on this repository.

**Comment by hs536** [comment]
> https://jenkins.eclipse.org/orb/job/orb-final-release is the job intended for that purpose.

Unfortunately, I don't have the authority to execute this job.

> 4.1.1 and 4.1.2 still haven't appeared on Maven Central, although they are tagged on this repository.

@russgold @smillidge Do you have any idea?

**Comment by hs536** [comment]
@smillidge @russgold Could you try to release the currently staged module to the Maven Central?

**Comment by smillidge** [comment]
which version?

**Comment by smillidge** [comment]
I released 4.1.1. Do you need a final 4.1.2?

**Comment by hs536** [comment]
for GlassFish JDK 11 support, 4.1.2 release is required that includes the following commits:
https://github.com/eclipse-ee4j/orb-gmbal-pfl/commit/dfca08b329dc578d28ef28c4fcfdf2cc626655a4

**Comment by smillidge** [comment]
I've staged a 4.1.2
