### ISSUE TITLE
Build CI/CD pipeline

### ISSUE THREAD

**Issue by m0mus** [eclipse-ee4j/orb-gmbal-pfl#5]
This task is for creating a basic build CI/CD pipeline for this project on Eclipse infrastructure. More information is here: https://ci.eclipse.org/.

**Comment by vinayvishal** [comment]
PR #10 raised having necessary changes (and some cleanup) for a successful build. Currently tests are skipped. Opened issue #9 for the same. Closing this one since this task is complete.

**Comment by vinayvishal** [comment]
Since the job is in place, this issue is being closed. I will be working in-parallel in any existing issues and towards first successful run of this job.

**Comment by vinayvishal** [comment]
Since the job is in place, this issue is being closed. I will be working in-parallel in any existing issues and towards first successful run of this job.
