### ISSUE TITLE
Release CI/CD pipeline

### ISSUE THREAD

**Issue by m0mus** [eclipse-ee4j/orb-gmbal-pfl#6]
We need to create a release CI/CD pipeline for this project. 

Use these documents as a reference:

- [How to release the first Eclipse version of projects](https://github.com/eclipse-ee4j/ee4j/wiki/How-to-release-the-first-Eclipse-version-of-projects)
- [JSONP release job](https://github.com/eclipse-ee4j/jsonp/wiki/JSONP-release-job)

**Comment by vinayvishal** [comment]
Both master build and release build jobs have been created. However, orb-gmbal has maven-toolchains-plugin configured which requires that toolchains.xml be present in ~/.m2 repository. It was needed for specific use cases when the project was part of JavaEE. We have sought for the inputs from experts if this requirement still holds true. If not, this plugin will be removed from the project's pom, else we will have to get this configured in corresponding jenkins instance.

**Comment by vinayvishal** [comment]
Since the job is in place, this issue is being closed. I will be working in-parallel in any existing issues and towards first successful run of this job.
